#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running ESLint..."
pnpm lint || { echo "ESLint check failed!"; exit 1; }

echo "Checking code formatting..."
pnpm prettier:check || { echo "Prettier check failed!"; exit 1; }
